---
- name: Working with inventory
  hosts: dev
  tasks:
    - name: copy the content to the banner
      ansible.builtin.copy:
        content: "Sun set down in east"
        dest: /etc/motd.d/banner
